"""Update

Revision ID: 884a74b11007
Revises: f867648e56f3
Create Date: 2024-10-27 21:07:02.808328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884a74b11007'
down_revision = 'f867648e56f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessmenttitle', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('modulecode', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.drop_index('ix_assessments_AssessmentTitle')
        batch_op.drop_index('ix_assessments_ModuleCode')
        batch_op.create_index(batch_op.f('ix_assessments_assessmenttitle'), ['assessmenttitle'], unique=True)
        batch_op.create_index(batch_op.f('ix_assessments_modulecode'), ['modulecode'], unique=True)
        batch_op.drop_column('AssessmentTitle')
        batch_op.drop_column('Completed')
        batch_op.drop_column('Deadline')
        batch_op.drop_column('ModuleCode')
        batch_op.drop_column('Description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ModuleCode', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('Deadline', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('Completed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('AssessmentTitle', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_index(batch_op.f('ix_assessments_modulecode'))
        batch_op.drop_index(batch_op.f('ix_assessments_assessmenttitle'))
        batch_op.create_index('ix_assessments_ModuleCode', ['ModuleCode'], unique=1)
        batch_op.create_index('ix_assessments_AssessmentTitle', ['AssessmentTitle'], unique=1)
        batch_op.drop_column('status')
        batch_op.drop_column('description')
        batch_op.drop_column('deadline')
        batch_op.drop_column('modulecode')
        batch_op.drop_column('assessmenttitle')

    # ### end Alembic commands ###
