"""new

Revision ID: f867648e56f3
Revises: 9ad59ba23795
Create Date: 2024-10-27 13:26:03.970695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f867648e56f3'
down_revision = '9ad59ba23795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('AssessmentTitle', sa.String(length=500), nullable=True),
    sa.Column('ModuleCode', sa.String(length=100), nullable=True),
    sa.Column('Deadline', sa.Date(), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_AssessmentTitle'), ['AssessmentTitle'], unique=True)
        batch_op.create_index(batch_op.f('ix_assessments_ModuleCode'), ['ModuleCode'], unique=True)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_property_address'), ['address'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_address'))
        batch_op.drop_column('address')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_ModuleCode'))
        batch_op.drop_index(batch_op.f('ix_assessments_AssessmentTitle'))

    op.drop_table('assessments')
    # ### end Alembic commands ###
